const axios = require('axios');
const crypto = require('crypto');
const config = require('../config/config');
const logger = require('../utils/logger');

class KeyAuthAPI {
    constructor() {
        this.name = config.keyauth.name;
        this.ownerId = config.keyauth.ownerId;
        this.version = config.keyauth.version;
        this.url = config.keyauth.url;
        this.secret = config.keyauth.secret;

        if (!this.secret) {
            throw new Error('KeyAuth secret not provided in environment variables');
        }

        this.sessionid = null;
        this.initialized = false;

        // Create axios instance
        this.client = axios.create({
            timeout: 10000,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'User-Agent': 'Discord-License-Bot/1.0'
            }
        });
    }

    /**
     * Initialize KeyAuth session
     * @returns {boolean} - True if initialization successful
     */
    async initialize() {
        try {
            logger.info('Initializing KeyAuth session...');

            const initData = {
                type: 'init',
                name: this.name,
                ownerid: this.ownerId,
                ver: this.version
            };

            const response = await this.client.post(this.url, new URLSearchParams(initData));
            const result = response.data;

            if (!result.success) {
                throw new Error(`KeyAuth initialization failed: ${result.message}`);
            }

            this.sessionid = result.sessionid;
            this.initialized = true;

            logger.info('KeyAuth initialized successfully');
            return true;

        } catch (error) {
            logger.error('KeyAuth initialization failed:', error.message);
            this.initialized = false;
            return false;
        }
    }

    /**
     * Ensure KeyAuth is initialized before making requests
     */
    async ensureInitialized() {
        if (!this.initialized) {
            const success = await this.initialize();
            if (!success) {
                throw new Error('Failed to initialize KeyAuth session');
            }
        }
    }

    /**
     * Create a new license key
     * @param {object} options - License creation options
     * @param {string} options.licenseKey - Custom license key (optional)
     * @param {number} options.expiry - Expiry in days (0 for lifetime)
     * @param {string} options.level - License level/tier
     * @param {string} options.note - Note for the license
     * @returns {object} - License creation result
     */
    async createLicense(options = {}) {
        try {
            await this.ensureInitialized();

            logger.info('Creating new KeyAuth license...');

            // Generate license key if not provided
            const licenseKey = options.licenseKey || this.generateLicenseKey();

            const licenseData = {
                type: 'add',
                sessionid: this.sessionid,
                format: 'JSON',
                key: licenseKey,
                expiry: options.expiry || 0, // 0 = lifetime
                level: options.level || '1',
                amount: 1, // Number of uses (1 for single-use)
                note: options.note || `Generated by Discord bot - ${new Date().toISOString()}`
            };

            const response = await this.client.post(this.url, new URLSearchParams(licenseData));
            const result = response.data;

            if (!result.success) {
                throw new Error(`License creation failed: ${result.message}`);
            }

            logger.info(`License created successfully: ${licenseKey}`);

            return {
                success: true,
                licenseKey: licenseKey,
                expiry: licenseData.expiry,
                level: licenseData.level,
                createdAt: new Date().toISOString(),
                keyAuthResponse: result
            };

        } catch (error) {
            logger.error('License creation failed:', error.message);
            return {
                success: false,
                error: error.message,
                licenseKey: null
            };
        }
    }

    /**
     * Delete a license key
     * @param {string} licenseKey - License key to delete
     * @returns {boolean} - True if deletion successful
     */
    async deleteLicense(licenseKey) {
        try {
            await this.ensureInitialized();

            logger.info(`Deleting license: ${licenseKey}`);

            const deleteData = {
                type: 'del',
                sessionid: this.sessionid,
                format: 'JSON',
                key: licenseKey
            };

            const response = await this.client.post(this.url, new URLSearchParams(deleteData));
            const result = response.data;

            if (!result.success) {
                logger.warn(`License deletion failed: ${result.message}`);
                return false;
            }

            logger.info(`License deleted successfully: ${licenseKey}`);
            return true;

        } catch (error) {
            logger.error('License deletion failed:', error.message);
            return false;
        }
    }

    /**
     * Verify a license key exists and is valid
     * @param {string} licenseKey - License key to verify
     * @returns {object} - Verification result
     */
    async verifyLicense(licenseKey) {
        try {
            await this.ensureInitialized();

            const verifyData = {
                type: 'license',
                sessionid: this.sessionid,
                format: 'JSON',
                key: licenseKey
            };

            const response = await this.client.post(this.url, new URLSearchParams(verifyData));
            const result = response.data;

            return {
                valid: result.success,
                message: result.message,
                info: result.info || null
            };

        } catch (error) {
            logger.error('License verification failed:', error.message);
            return {
                valid: false,
                message: error.message,
                info: null
            };
        }
    }

    /**
     * Get application statistics
     * @returns {object} - Application stats
     */
    async getStats() {
        try {
            await this.ensureInitialized();

            const statsData = {
                type: 'fetchStats',
                sessionid: this.sessionid,
                format: 'JSON'
            };

            const response = await this.client.post(this.url, new URLSearchParams(statsData));
            const result = response.data;

            if (!result.success) {
                throw new Error(`Failed to fetch stats: ${result.message}`);
            }

            return {
                success: true,
                stats: result.appinfo
            };

        } catch (error) {
            logger.error('Failed to get KeyAuth stats:', error.message);
            return {
                success: false,
                error: error.message
            };
        }
    }

    /**
     * Generate a secure license key
     * @param {number} length - Length of the license key
     * @returns {string} - Generated license key
     */
    generateLicenseKey(length = 24) {
        const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        let result = '';

        // Generate random characters
        for (let i = 0; i < length; i++) {
            result += characters.charAt(Math.floor(Math.random() * characters.length));
        }

        // Format as groups of 4 characters separated by hyphens
        return result.replace(/.{4}/g, '$&-').slice(0, -1);
    }

    /**
     * Create a license specifically for Discord bot redemption
     * @param {string} invoiceId - Invoice ID for tracking
     * @param {string} discordUserId - Discord user ID
     * @param {object} invoiceData - SellAuth invoice data
     * @returns {object} - License creation result
     */
    async createLicenseForRedemption(invoiceId, discordUserId, invoiceData) {
        try {
            const licenseKey = this.generateLicenseKey();

            const note = JSON.stringify({
                source: 'discord_bot',
                invoiceId: invoiceId,
                discordUserId: discordUserId,
                productName: invoiceData.product_name || 'Unknown',
                amount: invoiceData.amount || 0,
                currency: invoiceData.currency || 'USD',
                redeemedAt: new Date().toISOString()
            });

            const result = await this.createLicense({
                licenseKey: licenseKey,
                expiry: 0, // Lifetime license as requested
                level: '1',
                note: note
            });

            if (result.success) {
                logger.info(`License created for redemption - Invoice: ${invoiceId}, User: ${discordUserId}, Key: ${licenseKey}`);
            }

            return result;

        } catch (error) {
            logger.error('Failed to create license for redemption:', error.message);
            return {
                success: false,
                error: error.message,
                licenseKey: null
            };
        }
    }

    /**
     * Test KeyAuth connection
     * @returns {boolean} - True if connection successful
     */
    async testConnection() {
        try {
            const success = await this.initialize();
            if (success) {
                // Reset initialization flag for future use
                this.initialized = false;
                this.sessionid = null;
            }
            return success;
        } catch (error) {
            logger.error('KeyAuth connection test failed:', error.message);
            return false;
        }
    }

    /**
     * Get license information
     * @param {string} licenseKey - License key to look up
     * @returns {object} - License information
     */
    async getLicenseInfo(licenseKey) {
        try {
            await this.ensureInitialized();

            const infoData = {
                type: 'getkey',
                sessionid: this.sessionid,
                format: 'JSON',
                key: licenseKey
            };

            const response = await this.client.post(this.url, new URLSearchParams(infoData));
            const result = response.data;

            return {
                success: result.success,
                info: result.keyinfo || null,
                message: result.message
            };

        } catch (error) {
            logger.error('Failed to get license info:', error.message);
            return {
                success: false,
                info: null,
                message: error.message
            };
        }
    }
}

module.exports = new KeyAuthAPI();